module.exports = {
	none: 0,
	discordEmployee: 1 << 0,
	partneredServerOwner: 1 << 1,
	hypeSquadEvents: 1 << 2,
	bugHunterLevel_1: 1 << 3,
	bugHunterLevel_2: 1 << 14,
	houseBravery: 1 << 6,
	houseBrilliance: 1 << 8,
	houseBalance: 1 << 9,
	earlySupporter: 1 << 9,
	teamUser: 1 << 10,
	verifiedBot: 1 << 16,
	earlyVerifiedBotDeveloper: 1 << 17,
};
